#############################################################################
# Makefile for building: test
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Sep 26 17:56:02 2017
# Project:  test.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile test.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)   -lglut -lGLEW -lGL -lGLU -lm -lstdc++ -lpng -lrt 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		CJRW.cpp \
		shadermanager.cpp \
		imagemanip.cpp \
		renderobject.cpp \
		modelmanager.cpp \
		physicsobject.cpp \
		physicsmanager.cpp \
		sphereobject.cpp \
		planeobject.cpp \
		function2d.cpp \
		linefunction.cpp 
OBJECTS       = main.o \
		CJRW.o \
		shadermanager.o \
		imagemanip.o \
		renderobject.o \
		modelmanager.o \
		physicsobject.o \
		physicsmanager.o \
		sphereobject.o \
		planeobject.o \
		function2d.o \
		linefunction.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		test.pro
QMAKE_TARGET  = test
DESTDIR       = 
TARGET        = test

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: test.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile test.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile test.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/test1.0.0 || $(MKDIR) .tmp/test1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/test1.0.0/ && (cd `dirname .tmp/test1.0.0` && $(TAR) test1.0.0.tar test1.0.0 && $(COMPRESS) test1.0.0.tar) && $(MOVE) `dirname .tmp/test1.0.0`/test1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp ../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h \
		../glm-0.9.8.5/glm/gtc/matrix_transform.hpp \
		../glm-0.9.8.5/glm/gtc/constants.hpp \
		../glm-0.9.8.5/glm/gtc/constants.inl \
		../glm-0.9.8.5/glm/gtc/matrix_transform.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.inl \
		../glm-0.9.8.5/glm/gtc/quaternion_simd.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.inl \
		../glm-0.9.8.5/glm/gtx/transform.hpp \
		../glm-0.9.8.5/glm/gtx/transform.inl \
		CJRW.h \
		structpile.h \
		shadermanager.h \
		renderobject.h \
		modelmanager.h \
		imagemanip.h \
		function2d.h \
		physicsobject.h \
		../glm-0.9.8.5/glm/gtx/rotate_vector.hpp \
		../glm-0.9.8.5/glm/gtx/rotate_vector.inl \
		physicsmanager.h \
		sphereobject.h \
		planeobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

CJRW.o: CJRW.cpp CJRW.h \
		structpile.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CJRW.o CJRW.cpp

shadermanager.o: shadermanager.cpp shadermanager.h \
		structpile.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h \
		renderobject.h \
		../glm-0.9.8.5/glm/gtc/matrix_transform.hpp \
		../glm-0.9.8.5/glm/gtc/constants.hpp \
		../glm-0.9.8.5/glm/gtc/constants.inl \
		../glm-0.9.8.5/glm/gtc/matrix_transform.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.inl \
		../glm-0.9.8.5/glm/gtc/quaternion_simd.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.inl \
		../glm-0.9.8.5/glm/gtx/transform.hpp \
		../glm-0.9.8.5/glm/gtx/transform.inl \
		modelmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shadermanager.o shadermanager.cpp

imagemanip.o: imagemanip.cpp imagemanip.h \
		function2d.h \
		structpile.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagemanip.o imagemanip.cpp

renderobject.o: renderobject.cpp renderobject.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h \
		../glm-0.9.8.5/glm/gtc/matrix_transform.hpp \
		../glm-0.9.8.5/glm/gtc/constants.hpp \
		../glm-0.9.8.5/glm/gtc/constants.inl \
		../glm-0.9.8.5/glm/gtc/matrix_transform.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.inl \
		../glm-0.9.8.5/glm/gtc/quaternion_simd.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.inl \
		../glm-0.9.8.5/glm/gtx/transform.hpp \
		../glm-0.9.8.5/glm/gtx/transform.inl \
		modelmanager.h \
		structpile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderobject.o renderobject.cpp

modelmanager.o: modelmanager.cpp modelmanager.h \
		structpile.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelmanager.o modelmanager.cpp

physicsobject.o: physicsobject.cpp physicsobject.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h \
		../glm-0.9.8.5/glm/gtc/matrix_transform.hpp \
		../glm-0.9.8.5/glm/gtc/constants.hpp \
		../glm-0.9.8.5/glm/gtc/constants.inl \
		../glm-0.9.8.5/glm/gtc/matrix_transform.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.inl \
		../glm-0.9.8.5/glm/gtc/quaternion_simd.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.inl \
		../glm-0.9.8.5/glm/gtx/transform.hpp \
		../glm-0.9.8.5/glm/gtx/transform.inl \
		../glm-0.9.8.5/glm/gtx/rotate_vector.hpp \
		../glm-0.9.8.5/glm/gtx/rotate_vector.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o physicsobject.o physicsobject.cpp

physicsmanager.o: physicsmanager.cpp physicsmanager.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h \
		../glm-0.9.8.5/glm/gtc/matrix_transform.hpp \
		../glm-0.9.8.5/glm/gtc/constants.hpp \
		../glm-0.9.8.5/glm/gtc/constants.inl \
		../glm-0.9.8.5/glm/gtc/matrix_transform.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.inl \
		../glm-0.9.8.5/glm/gtc/quaternion_simd.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.inl \
		../glm-0.9.8.5/glm/gtx/transform.hpp \
		../glm-0.9.8.5/glm/gtx/transform.inl \
		physicsobject.h \
		../glm-0.9.8.5/glm/gtx/rotate_vector.hpp \
		../glm-0.9.8.5/glm/gtx/rotate_vector.inl \
		sphereobject.h \
		planeobject.h \
		structpile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o physicsmanager.o physicsmanager.cpp

sphereobject.o: sphereobject.cpp sphereobject.h \
		physicsobject.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h \
		../glm-0.9.8.5/glm/gtc/matrix_transform.hpp \
		../glm-0.9.8.5/glm/gtc/constants.hpp \
		../glm-0.9.8.5/glm/gtc/constants.inl \
		../glm-0.9.8.5/glm/gtc/matrix_transform.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.inl \
		../glm-0.9.8.5/glm/gtc/quaternion_simd.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.inl \
		../glm-0.9.8.5/glm/gtx/transform.hpp \
		../glm-0.9.8.5/glm/gtx/transform.inl \
		../glm-0.9.8.5/glm/gtx/rotate_vector.hpp \
		../glm-0.9.8.5/glm/gtx/rotate_vector.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sphereobject.o sphereobject.cpp

planeobject.o: planeobject.cpp planeobject.h \
		physicsobject.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h \
		../glm-0.9.8.5/glm/gtc/matrix_transform.hpp \
		../glm-0.9.8.5/glm/gtc/constants.hpp \
		../glm-0.9.8.5/glm/gtc/constants.inl \
		../glm-0.9.8.5/glm/gtc/matrix_transform.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.hpp \
		../glm-0.9.8.5/glm/gtc/quaternion.inl \
		../glm-0.9.8.5/glm/gtc/quaternion_simd.inl \
		../glm-0.9.8.5/glm/gtc/type_ptr.inl \
		../glm-0.9.8.5/glm/gtx/transform.hpp \
		../glm-0.9.8.5/glm/gtx/transform.inl \
		../glm-0.9.8.5/glm/gtx/rotate_vector.hpp \
		../glm-0.9.8.5/glm/gtx/rotate_vector.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o planeobject.o planeobject.cpp

function2d.o: function2d.cpp function2d.h \
		structpile.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o function2d.o function2d.cpp

linefunction.o: linefunction.cpp linefunction.h \
		function2d.h \
		structpile.h \
		../glm-0.9.8.5/glm/glm.hpp \
		../glm-0.9.8.5/glm/detail/_fixes.hpp \
		../glm-0.9.8.5/glm/fwd.hpp \
		../glm-0.9.8.5/glm/detail/type_int.hpp \
		../glm-0.9.8.5/glm/detail/setup.hpp \
		../glm-0.9.8.5/glm/simd/platform.h \
		../glm-0.9.8.5/glm/detail/type_float.hpp \
		../glm-0.9.8.5/glm/detail/type_vec.hpp \
		../glm-0.9.8.5/glm/detail/precision.hpp \
		../glm-0.9.8.5/glm/detail/type_mat.hpp \
		../glm-0.9.8.5/glm/vec2.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle.hpp \
		../glm-0.9.8.5/glm/detail/_swizzle_func.hpp \
		../glm-0.9.8.5/glm/detail/type_vec2.inl \
		../glm-0.9.8.5/glm/vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.hpp \
		../glm-0.9.8.5/glm/detail/type_vec3.inl \
		../glm-0.9.8.5/glm/vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.hpp \
		../glm-0.9.8.5/glm/detail/type_vec4.inl \
		../glm-0.9.8.5/glm/detail/type_vec4_simd.inl \
		../glm-0.9.8.5/glm/mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x2.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.hpp \
		../glm-0.9.8.5/glm/mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x3.inl \
		../glm-0.9.8.5/glm/mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat2x4.inl \
		../glm-0.9.8.5/glm/mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x2.inl \
		../glm-0.9.8.5/glm/mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x3.inl \
		../glm-0.9.8.5/glm/mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat3x4.inl \
		../glm-0.9.8.5/glm/mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x2.inl \
		../glm-0.9.8.5/glm/mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x3.inl \
		../glm-0.9.8.5/glm/mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.hpp \
		../glm-0.9.8.5/glm/detail/type_mat4x4.inl \
		../glm-0.9.8.5/glm/detail/type_mat4x4_simd.inl \
		../glm-0.9.8.5/glm/detail/func_matrix.inl \
		../glm-0.9.8.5/glm/geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.hpp \
		../glm-0.9.8.5/glm/detail/func_geometric.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.hpp \
		../glm-0.9.8.5/glm/detail/type_vec1.inl \
		../glm-0.9.8.5/glm/detail/func_exponential.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational.hpp \
		../glm-0.9.8.5/glm/detail/func_vector_relational.inl \
		../glm-0.9.8.5/glm/detail/func_vector_relational_simd.inl \
		../glm-0.9.8.5/glm/detail/_vectorize.hpp \
		../glm-0.9.8.5/glm/detail/func_exponential_simd.inl \
		../glm-0.9.8.5/glm/simd/exponential.h \
		../glm-0.9.8.5/glm/detail/func_common.hpp \
		../glm-0.9.8.5/glm/detail/func_common.inl \
		../glm-0.9.8.5/glm/detail/func_common_simd.inl \
		../glm-0.9.8.5/glm/simd/common.h \
		../glm-0.9.8.5/glm/detail/func_geometric_simd.inl \
		../glm-0.9.8.5/glm/simd/geometric.h \
		../glm-0.9.8.5/glm/detail/func_matrix_simd.inl \
		../glm-0.9.8.5/glm/simd/matrix.h \
		../glm-0.9.8.5/glm/trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.hpp \
		../glm-0.9.8.5/glm/detail/func_trigonometric.inl \
		../glm-0.9.8.5/glm/detail/func_trigonometric_simd.inl \
		../glm-0.9.8.5/glm/exponential.hpp \
		../glm-0.9.8.5/glm/common.hpp \
		../glm-0.9.8.5/glm/packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.hpp \
		../glm-0.9.8.5/glm/detail/func_packing.inl \
		../glm-0.9.8.5/glm/detail/type_half.hpp \
		../glm-0.9.8.5/glm/detail/type_half.inl \
		../glm-0.9.8.5/glm/detail/func_packing_simd.inl \
		../glm-0.9.8.5/glm/matrix.hpp \
		../glm-0.9.8.5/glm/vector_relational.hpp \
		../glm-0.9.8.5/glm/integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.hpp \
		../glm-0.9.8.5/glm/detail/func_integer.inl \
		../glm-0.9.8.5/glm/detail/func_integer_simd.inl \
		../glm-0.9.8.5/glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linefunction.o linefunction.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

